### ISSUE TITLE
랜딩 페이지 밥이 보약 섹션

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#11]
섹션 범위 설정
내부 문자 크기 및 기울기 설정

**Comment by onlydel** [comment]
제목에 `중단부` 보다는 섹션별로 이름(별명)을 붙이면 서로 이해하기가 쉬울것 같은데, 어떨까요?

예를 들면,

- 첫 번째 페이지 => 랜딩 페이지
- 캐로셀 들어가는 영역 => 히어로 섹션 (보통 이부분을 hreo section 으로 부른답니다.)
- 중단부 컨테이너 => 밥이보약 섹션
- 세번째 섹션 => 시작한 이유 섹션
- ...

랜딩 페이지 밥이 보약 섹션 #11

섹션 범위 설정
내부 문자 크기 및 기울기 설정

이런 느낌으로 괜찮을까요?
