### ISSUE TITLE
브라우저 뷰포트 크기를 변경해 보면 콘솔에 오류가 표시됩니다.

### ISSUE THREAD

**Issue by onlydel** [wooritech/woori-camp-mission-01#15]
### 현상

- 영상의 오른쪽 아래 콘솔창에 오류 표시

https://github.com/wooritech/wooricamp-mission/assets/6207238/74e82d36-2107-4e1c-bbeb-f5c09d09f8c9

### 오류 메시지

<img width="489" alt="image" src="https://github.com/wooritech/wooricamp-mission/assets/6207238/7377e334-8f71-451a-a9e5-9a450b0f739b">

**Comment by Malloc72P** [comment]
리뷰할때 좀 더 꼼꼼히 봤어야 했는데...

**Comment by Hjname** [comment]
저도 콘솔 확인할 생각을 못했네요...

**Comment by onlydel** [comment]
저 에러 메시지는 무슨 의미인가요?
어디가면 에러에 대한 내용을 찾을 수 있을 까용?

**Comment by Hjname** [comment]
> 저 에러 메시지는 무슨 의미인가요? 어디가면 에러에 대한 내용을 찾을 수 있을 까용?

const변수에 새로운 값이 들어가서 발생한 변수입니다.
```js
// js 9번 라인의
const slideWidth = slide.clientWidth; //를 
let slideWidth = slide.clientWidth; //로 변경하였습니다.
```

**Comment by onlydel** [comment]
에러에 대한 정의는 여기에 있네요.
역시 MDN은 웹 개발 교과서 같습니다.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_const_assignment

간략히 보면 
> "const 즉 상수의 값을 변경하려고 할 때 예외가 발생한다."
> "JavaScript의 상수 즉 const 선언은 다시 할당하거나 다시 선언할 수 없다" 

라고 되어 있고 맨 아래로 내려가 보면 object의 경우 속성값 변경에 대한 예외 사항도 있네요.

이렇게 보면서 또 복습 하면 좋겠죠? 🎊
