### ISSUE TITLE
두번째 케러셀 이미지 작업

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#16]
메인 페이지의 두번째 캐러셀 이미지를 작업한다.

- 이전에 작성한 캐러셀과 비교하며 작성한다.

**Comment by Malloc72P** [comment]
해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!

이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다

**Comment by Hjname** [comment]
> 해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!
> 
> 이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다

이미지 작업 완료후 동작을 추가하는 과정에서 문제가 발생해서 수정하는 중입니다.

**Comment by Malloc72P** [comment]
> > 해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!
> > 이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다
> 
> 이미지 작업 완료후 동작을 추가하는 과정에서 문제가 발생해서 수정하는 중입니다.

음... 그러면 해당 이슈는 완료된 거 아닌가요?

동작에 대한 작업은 #17번 이슈에서 하는 것 같은데요

**Comment by Hjname** [comment]
> > > 해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!
> > > 이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다
> > 
> > 
> > 이미지 작업 완료후 동작을 추가하는 과정에서 문제가 발생해서 수정하는 중입니다.
> 
> 음... 그러면 해당 이슈는 완료된 거 아닌가요?
> 
> 동작에 대한 작업은 #17번 이슈에서 하는 것 같은데요

그러면... 이미지 작업 이슈는 완료처리하고 동작작업 이어가겠습니다.

**Comment by Malloc72P** [comment]
> > > > 해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!
> > > > 이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다
> > > 
> > > 
> > > 이미지 작업 완료후 동작을 추가하는 과정에서 문제가 발생해서 수정하는 중입니다.
> > 
> > 
> > 음... 그러면 해당 이슈는 완료된 거 아닌가요?
> > 동작에 대한 작업은 #17번 이슈에서 하는 것 같은데요
> 
> 그러면... 이미지 작업 이슈는 완료처리하고 동작작업 이어가겠습니다.

아뇨아뇨 제 말은 해당 이슈가 완료되었는데 PR이 안올라와서 하는 말이었어요

우리 미션 시작할 때 이슈 하나랑 PR 하나 연결해서 하기로 했었던 것 같은데 아니었나요?

**Comment by Hjname** [comment]
> > > > > 해당 이슈는 화요일 완료 예정이었는데 아직 작업중인것 보니까, 뭔가 막히는 부분이 있나보네요!
> > > > > 이럴땐 코멘트로 어떤 사유 때문에 지연되고 있는지 공유해주면 좋을 것 같습니다
> > > > 
> > > > 
> > > > 이미지 작업 완료후 동작을 추가하는 과정에서 문제가 발생해서 수정하는 중입니다.
> > > 
> > > 
> > > 음... 그러면 해당 이슈는 완료된 거 아닌가요?
> > > 동작에 대한 작업은 #17번 이슈에서 하는 것 같은데요
> > 
> > 
> > 그러면... 이미지 작업 이슈는 완료처리하고 동작작업 이어가겠습니다.
> 
> 아뇨아뇨 제 말은 해당 이슈가 완료되었는데 PR이 안올라와서 하는 말이었어요
> 
> 우리 미션 시작할 때 이슈 하나랑 PR 하나 연결해서 하기로 했었던 것 같은데 아니었나요?

아 그런 말씀이셨군요. 저도 이미지 작업 완료후 pr을 올릴려고 했는데 밥이 보약이 끝나지 않은 상태여서 먼저 동작 작업을 하다보니 이미지가 이상하게 나오는 경우가 생겨서 수정중이었습니다. 그럼 우선 이미지 먼저 pr 올리겠습니다.

**Comment by onlydel** [comment]
### 질문 🙋

- "캐러셀2 이미지를 페이지에 표시 하는 것"이 이 이슈의 내용인 거지요? (작업 한다? 라는 말이 정확히 이해되지 않아서요~)
- 이미지는 아래 다섯개 구요?
  - [banner2-01.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-01.jpeg)
  - [banner2-02.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-02.jpeg)
  - [banner2-03.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-03.jpeg)
  - [banner2-04.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-04.jpeg)
  - [banner2-05.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-05.jpeg)

**Comment by Hjname** [comment]
> ### 질문 🙋
> * "캐러셀2 이미지를 페이지에 표시 하는 것"이 이 이슈의 내용인 거지요? (작업 한다? 라는 말이 정확히 이해되지 않아서요~)
> * 이미지는 아래 다섯개 구요?
>   
>   * [banner2-01.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-01.jpeg)
>   * [banner2-02.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-02.jpeg)
>   * [banner2-03.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-03.jpeg)
>   * [banner2-04.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-04.jpeg)
>   * [banner2-05.jpeg](https://github.com/wooritech/wooricamp-mission/blob/8f7d78a232d62eb00d278d3252623b40789be337/public/banner2-05.jpeg)

네, 맞습니다.

**Comment by onlydel** [comment]
작업 한다는 보통 조폭들이 쓸모없는 사람을 슉~슉~ 🔪 할때 쓰거나 이성에게 찝쩍 거릴때 쓰는 용어.... 라는.... 😂

**Comment by onlydel** [comment]
난 슬랙 알림이 안오는 걸까? 이 저장소에서....

**Comment by Hjname** [comment]
> 작업 한다는 보통 조폭들이 쓸모없는 사람을 슉~슉~ 🔪 할때 쓰거나 이성에게 찝쩍 거릴때 쓰는 용어.... 라는.... 😂

다음부터는 코딩한다. 라고 하겠습니다 ㅎㅎ

**Comment by onlydel** [comment]
ㅋㅋ 그 단어 자체 보다는

"작업한다." 를
어떤 작업을 하는 것인지 좀더 상세한 내용을 기술하면 좋을것 같습니다.

위에 내가 얘기 한것 처럼, 

**"이미지를 페이지에 올리는 작업이고 이미지는 머머머다..."**

뭐 이런정도로 말이죠.

**Comment by Hjname** [comment]
> ㅋㅋ 그 단어 자체 보다는
> 
> "작업한다." 를 어떤 작업을 하는 것인지 좀더 상세한 내용을 기술하면 좋을것 같습니다.
> 
> 위에 내가 얘기 한것 처럼,
> 
> **"이미지를 페이지에 올리는 작업이고 이미지는 머머머다..."**
> 
> 뭐 이런정도로 말이죠.

아... 그런 말씀이셨구나... 그럼 이번 이슈의 경우에는 예를 들어 "메인페이지 두번째 캐러셀의 이미지를 작성한다. 이미지의 예는 
<img width="672" alt="image" src="https://github.com/wooritech/wooricamp-mission/assets/152573932/0043abfa-f6e9-4adf-84c6-6ccf7d2eff9c"> 이다." 이렇게 말씀이시죠?
