### ISSUE TITLE
두번째 캐러셀 동작 작업

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#17]
작성한 캐러셀 이미지를 동작 시킨다.

- 이전 작성한 캐러셀과 비교하여 작성한다.
- 하나의 페이지에 복수의 캐러셀이 들어갔다는것을 유의하며 작성한다.

**Comment by Malloc72P** [comment]
해당 이슈도 https://github.com/wooritech/wooricamp-mission/issues/16#issuecomment-1920296485 와 마찬가지로 예정된 완료시간보다 지연되는 경우, 코멘트로 어떤 어려움이 있는지 공유해주세요!

작업이 어떻게 진행되고 있는지, 막히는 부분은 없는지 팀과 공유하면 좋을 것 같아요 👍

**Comment by Hjname** [comment]
> 해당 이슈도 [#16 (comment)](https://github.com/wooritech/wooricamp-mission/issues/16#issuecomment-1920296485) 와 마찬가지로 예정된 완료시간보다 지연되는 경우, 코멘트로 어떤 어려움이 있는지 공유해주세요!
> 
> 작업이 어떻게 진행되고 있는지, 막히는 부분은 없는지 팀과 공유하면 좋을 것 같아요 👍

네 알겠습니다!
