### ISSUE TITLE
캐러셀 동작에 관련 문의 이슈

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#21]
1. 하단 페이지네이션 클릭 이동시 setinterval에서 설정한 딜레이 값이 초기화 되지 않는 문제
2. 하단 페이지네이션 클릭 이동시 자동슬라이드 위치가 이동 전 위치를 기준으로 작동하는 문제

https://github.com/wooritech/wooricamp-mission/assets/152573932/a01bdf67-ee14-4002-b5b5-0b5b139e44e5

해당하는 코드는 아래입니다.

```js
let counter = 2;
const delay = 6000;

setInterval(function(){
  document.getElementById('radio' + counter).checked = true;
  counter++;
  // counter의 크기가 이미지의 개수를 초과할 경우
  if(counter > 5){
    // counter를 1로 초기화
    counter = 1;
  } else {
    manual.addEventListener("click", () => {
      delay = 6000;
    });
  }
  //자동 슬라이드 딜레이
}, delay);
```

**Comment by Malloc72P** [comment]
> _하단 페이지네이션 클릭 이동시 setinterval에서 설정한 딜레이 값이 초기화 되지 않는 문제_

- 위의 코드에서 어떤 부분에서 딜레이를 초기화 하고 있나요?
- 한번 위의 코드를 가지고 플로우 차트를 그려보는게 좋을 것 같네요
- 직접 플로우 차트를 그려보면 도움이 될 것 같네요! 혹시 플로우차트 그려본 적 있나요?

> _하단 페이지네이션 클릭 이동시 자동슬라이드 위치가 이동 전 위치를 기준으로 작동하는 문제_

- 왜 이렇게 동작할까요? @Hjname님 생각엔 왜 이런 현상이 나타날 것 같아요?
- 한가지 힌트를 드리면... 클릭이 먼저였을까요 아니면 setInterval의 호출이 먼저였을까요? 만약 아주아주 미세한 차이로, 한 1밀리세컨드(ms) 차이로 setInterval 호출이 먼저였다면 어떻게 동작할까요?

**Comment by Hjname** [comment]
> > _하단 페이지네이션 클릭 이동시 setinterval에서 설정한 딜레이 값이 초기화 되지 않는 문제_
> 
> * 위의 코드에서 어떤 부분에서 딜레이를 초기화 하고 있나요?
> * 한번 위의 코드를 가지고 플로우 차트를 그려보는게 좋을 것 같네요
> * 직접 플로우 차트를 그려보면 도움이 될 것 같네요! 혹시 플로우차트 그려본 적 있나요?

딜레이 초기화는 해당 코딩을 추가하여 초기화 하려다가 실패하였습니다.

```js
const manual = document.querySelectorAll(".manual-btn");

setInterval(function(){
  document.getElementById('radio' + counter).checked = true;
  counter++;
  manual.addEventListener("click", () => {
    delay = 6000;
  });
```
페이지네이션 버튼인 manual-btn을 클릭하면 딜레이가 6초가 되도록 하였습니다.

위의 코드의 else문 부분과 동일한 코드입니다. 둘다 시도해봤지만 원했던 결과는 나오지 않았습니다.

**Comment by Malloc72P** [comment]
> > > _하단 페이지네이션 클릭 이동시 setinterval에서 설정한 딜레이 값이 초기화 되지 않는 문제_
> > 
> > 
> > 
> > * 위의 코드에서 어떤 부분에서 딜레이를 초기화 하고 있나요?
> > * 한번 위의 코드를 가지고 플로우 차트를 그려보는게 좋을 것 같네요
> > * 직접 플로우 차트를 그려보면 도움이 될 것 같네요! 혹시 플로우차트 그려본 적 있나요?
> 
> 딜레이 초기화는 해당 코딩을 추가하여 초기화 하려다가 실패하였습니다.
> 
> ```js
> const manual = document.querySelectorAll(".manual-btn");
> 
> setInterval(function(){
>   document.getElementById('radio' + counter).checked = true;
>   counter++;
>   manual.addEventListener("click", () => {
>     delay = 6000;
>   });
> ```
> 
> 페이지네이션 버튼인 manual-btn을 클릭하면 딜레이가 6초가 되도록 하였습니다.

`.manual-btn`이라는 클래스를 가진 요소는 한개인가요? 여러개인가요?

그리고 querySelectorAll의 리턴 타입은 [유사배열](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll#return_value)인 걸로 알고 있어요
그런데 위의 코드를 보면 `querySelectorAll`의 반환값을 저장한 `manual`에서 `addEventListener`메서드를 호출하고 있네요
혹시 이 부분에서 에러나지 않나요? 
콜백이 아예 등록이 안되었을 것 같네요. delay를 6초로 세팅하는 화살표 함수가 호출은 되고 있는지 한번 확인해보세요

**Comment by Malloc72P** [comment]
그리고 한가지 더...

delay 변수에 6000을 할당한다고 해서 이미 실행된 인터벌의 호출 간격이 변경될까요?

**Comment by Malloc72P** [comment]
한번 이 예제를 실행해보세요

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
</body>

<script>
    const buttons = document.querySelectorAll('button')
    let delay = 1000
    console.time()

    setInterval(() => {
        console.timeEnd()
        console.log('ping');
        delay += 1000
        console.time()
    }, delay)
</script>
</html>

```

https://github.com/wooritech/wooricamp-mission/assets/41663269/0843f99d-97dd-40e3-9e34-e504bf7d15f6

- 위의 예제를 보면, delay에 해당하는 변수의 값을 변경해도 이미 실행된 인터벌의 실행 간격은 변하지 않습니다

ps. 이미 실행된 인터벌을 종료시킬 순 있습니다. [clearInterval](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval)을 찾아보세요
