### ISSUE TITLE
코드 리팩토링 1 : 중복 코드 제거작업

### ISSUE THREAD

**Issue by Malloc72P** [wooritech/woori-camp-mission-01#25]
### 작업 요약

- 캐로셀을 구현한 main.js의 중복코드를 제거해봅시다

**Comment by Hjname** [comment]
캐러셀1, 2를 각각 코딩하는게 아니라 딜레이와, 변환시간을 제외한 부분을 하나의 모듈로 작성하여 반복 사용가능하게 만들것
그러기 위해서 캐러셀2 중복 코드 제거중 버튼이동시 딜레이 초기화가 안되는 문제 발생

**Comment by Hjname** [comment]
캐러셀 동작시 마지막 이미지에서 시작 delay값이 지난후 transition없이 2번 슬라이드로 이동 후 정상 작동
