### ISSUE TITLE
public 디렉토리에 이미지 파일 따로 모아 넣기

### ISSUE THREAD

**Issue by onlydel** [wooritech/woori-camp-mission-01#27]
### public 디렉토리에 이미지 파일 관리

- 일반적으로 웹 페이지 개발에서 `public` 폴더는 이미지, 텍스트 파일 등 정적인 파일을 넣어서 사용합니다.
- 단지 지금 구조에서 이미지 파일이 public 바로 밑에 펼쳐져 있는데
- 일반적으로 public/images 디렉토리를 만들고 그 아래에 또 하위 디렉토리들 만드는 방법으로 이미지 파일 관리를 합니다.
- 👉 이미지 파일의 디렉토리 구조를 조정해 보면 좋겠습니다.

### 깃헙에서 사용하는 이미지 파일

- 이미지 파일에 대한 얘기가 나왔으니까 얘기 하자면...
- readme-in-img 라는 디렉토리는 아마 readme 파일에서 사용하는 이미지 같은데요.
- 이런 파일은 보통 `.github` 이라는 이름의 디렉토리를 만들고 그곳에 모아 둡니다.
- 👉 이미지 파일이니까 .github/images 밑에 넣어두면 좋겠네요.

**Comment by onlydel** [comment]
이슈의 글속에 `"일반적으로"` `"보통"` 과 같은 용어들이 있는데,
이 말은 `"꼭 그렇게 하지 않아도 문제는 생기지 않는다. 하지만, 최소한 우리는 그렇게 해야 한다."` 의 의미로 약간의 강제성이 있음으로 이해하면 좋겠습니다.

**Comment by onlydel** [comment]
이 이슈도 #26 PR로 해결 된거면 close 해 주세요.

**Comment by onlydel** [comment]
아.. 아직 첫번째 이슈는 해결이 안된거네요.

**Comment by onlydel** [comment]
해결 된건가요?

**Comment by Hjname** [comment]
> 해결 된건가요?

네, 이미지 파일 이동하고 푸시했습니다.
