### ISSUE TITLE
첫번째 페이지 header 작성하기

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#3]
push를 wooritech/ wooricamp-mission으로 연결한다.
우리펫 푸드의 첫번째 페이지의 헤더 부분을 작성한다.

**Comment by Malloc72P** [comment]
딱 적당한 크기의 이슈가 만들어졌군요!

화이팅이예요!!! 🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by Malloc72P** [comment]
이슈의 Assignees, Projects 설정도 잊지 말아주세요~~~

**Comment by Malloc72P** [comment]
해당 이슈는 #5 Pull Request와 연결된 이슈이지요

이런 경우, 해당 PR이 완료된 다음에 닫아주어야 해요!

작업이 완료된 시점은 PR이 병합된 시점이니까요

그런 이유로, 해당 이슈는 다시 열겠습니다!

**Comment by Malloc72P** [comment]
### 풀 리퀘스트가 완료되었네요! 고생 많았어요 🚀🚀🚀

**다시 한번 리마인드하면, 깃헙을 통한 업무 프로세스는 아래와 같아요** 

1. 작업에 대한 이슈 생성
2. 작업에 대한 브랜치 생성
3. 작업 완료 후 해당 브랜치를 사용하여 풀 리퀘스트 생성
4. 코드리뷰를 통해 풀 리퀘스트 완료 후 병합
5. 작업에 대한 이슈 닫기(Close)

이런 흐름을 처음부터 끝까지 진행해보신거예요

앞으로도 계속 이런 방식으로 작업을 하시면 됩니다!

이제 #5 PR이 완료되었으니, 해당 이슈는 닫아주시면 됩니다~
